### ISSUE TITLE
Plutôt react-dsfr (que react_dsfr) ?

### ISSUE THREAD

**Issue by bzg** [codegouvfr/react_dsfr#1]
Je ne suis pas sûr du meilleur nom.

**Comment by garronej** [comment]
Je suis d'accord avec toi mais c'est juste que Deno interdi les `-` dans les nom des modules... 
Du coup je me suis dit que j'allais choisir un nom qui allais pouvoir être le même sur NPM et sur [deno.land/x](https://deno.land/x)

**Comment by bzg** [comment]
OK, pas de souci !
